apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../production/
images:
- digest: sha256:b3bba0e21cc05107e527907ae6bd06250b3ddd4ae6b12ab53e778d9047956b46
  name: image-registry.openshift-image-registry.svc:5000/oqss-hom/eap-app:latest
  newName: image-registry.openshift-image-registry.svc:5000/oqss-hom/eap-app
